### ISSUE TITLE
Better UI for running the tests

### ISSUE THREAD

**Issue by judy2k** [Vonage/vonage-python-code-snippets#10]
Whichever solution we choose for running the quickstarts, whether via the browser or the command-line, we should have a better UI for running the code. The supporting code for this should be clearly separated from the quickstart code itself, but also easily understood.

**Comment by lornajane** [comment]
One for @dragonmantank maybe?

**Comment by dragonmantank** [comment]
This is something I've actually started and stopped a few times internally, as we need a consistent way to run all of our code snippets in an automated manner as well. Not only do we use the snippets on the documentation website, but they serve as a first line of checking for SDK updates. I'll leave this open for now, and link to what we end up doing.

**Comment by yyprince334** [comment]
One for @dragonmantank maybe?

**Comment by dragonmantank** [comment]
This is indeed one we are working on internally, as it will be part of our CI pipeline. We'll open source what we can once it's done.
