### ISSUE TITLE
How to Verify 2FA code from my bank using my Vonage Virtual mobile number

### ISSUE THREAD

**Issue by bhimjipatel** [Vonage/vonage-python-code-snippets#146]
my Vonage-virtual phone number can receive SMS-text message fom my phone number 
(I receive it at AWS API-Gateway endpoint: https://MY-END-POINT.execute-api.us-east-1.amazonaws.com/v1/PROXY
(Please note: PROXY can receive anything after v1/ e.g webhooks/inbound-message or webhooks/inbound-sms
I want to receive Bank 2FA verification code  into my AWS API-Gateway endpoint, 
HOW CAN I RECEIVE BANK 2FA VERIFICATION CODE sent from my bank, to MY Vonage Virtual mobile number, and then how can I redirect it to my AWS-Gateway-endpoint ?

**Comment by dragonmantank** [comment]
Unfortunately you cannot use Vonage virtual numbers to receive identification texts like One Time Passwords. Please see our support article at https://api.support.vonage.com/hc/en-us/articles/360025314211-Why-are-Verification-Codes-not-received-on-my-virtual-number- for more info, but attempting to use a virtual number as an OTP endpoint is against our Terms of Service and Acceptable Use Policy.
