### ISSUE TITLE
Bug in generate_application_jwt function in jwt.py file

### ISSUE THREAD

**Issue by piotr-wasilewski** [Vonage/vonage-python-code-snippets#184]
There is a bug. More here

https://github.com/Vonage/vonage-python-jwt/issues/6

**Comment by maxkahan** [comment]
Hi, have responded on the other repo, I'm not sure this is a bug. I think you're providing a blank token. I'll close this issue as I've replied on the other repo, please respond [on the vonage-python-jwt repo](https://github.com/Vonage/vonage-python-jwt/issues/6) to confirm if my comment there fixed the issue or if you still need help.
