### ISSUE TITLE
how to know that audio played finished using send_audio

### ISSUE THREAD

**Issue by softsan** [Vonage/vonage-python-code-snippets#53]
I have following sequence:

- Caller calls a number (inbound call)
- it is answered
- we have another api from where we get the text and convert it to speech and then give that audio to play in call using client.send_audio
- So our api may send End call command and a sentence , so if i receive that i need to first play the audio (Converted from that sentence(text) to speech and give it client.send_audio) and then end the call (hangup)
- so in above, how can we know that audio is finished playing so that i can then End the call. currenly what happend that i do get a response from play_audio as stream started but i don't have any status whether audio is finished playing

following is my piece of code:

```
def on_final_result(self, text):
                if len(api_response["data"]["system_output"])>0:
                    text_to_speech = api_response["data"]["system_output"] # Receive sentence to speak from my api
                    file_url = self.pollyaudio(text_to_speech) # this will convert text to speech using polly
                    response = client.send_audio(os.environ['uuid'], stream_url=[file_url])
                    if response is not None:
                        time.sleep(10) # i am trying this but it is not working as expected

                command = api_response["data"]["commands"][0]
                # End of call command
                if command is not None and command['name'] == 'EOC':
                    client.update_call(os.environ['uuid'], action='hangup')
```

**Comment by lornajane** [comment]
( see also similar/related issue https://github.com/Nexmo/nexmo-python/issues/125 )

**Comment by softsan** [comment]
@lornajane It is also open by me. :)

**Comment by superdiana** [comment]
The previous issue that was opened was resolved. I will close this one too.
